Ladders/Server/config/routes.rb
Server::Application.routes.draw do

  resources :trades

end

Ladders/Server/app/models/trade.rb
class Trade < ActiveRecord::Base
  attr_accessible :id,
                  :executed_at,
                  :filled_at,
                  :is_executed,
                  :is_filled,
                  :longTrue_shortFalse,
                  :entered_price,
                  :filled_price,
                  :product_name,
                  :user,
                  :trade_queue_id
  belongs_to  :trade_queue
  before_save :try_execute

private  
  def try_execute
    self.assign_attributes({:is_executed => true, :executed_at => DateTime.now})
    if(is_filled == false)
      trade_queue.queue_trade self
    end
  end
end

Ladders/Server/app/models/trade_queue.rb
# an extremely simplified exchange, maintains a queue of trades;
# when an order is entered,
#  if it's a sell below the bid or a buy above the ask (ie, a market order)
#   match with the oldest instance of the highest bid or lowest ask,
#   respectively
#  otherwise it is queued at the desired price

class TradeQueue < ActiveRecord::Base
  attr_accessible :is_active, :product_name, :high_bid, :low_offer
  attr_accessor :high_bid, :low_offer
  has_many :trades
#  belongs_to :product
  def queue_trade aTrade
    if aTrade.longTrue_shortFalse == true
      et = trades.where([
        "entered_price <= ? AND longTrue_shortFalse == ? AND is_filled == ?",
        aTrade.entered_price, false, false
      ]).first
    elsif aTrade.longTrue_shortFalse == false
      et = trades.where([
        "entered_price >= ? AND longTrue_shortFalse == ? AND is_filled == ?",
        aTrade.entered_price, true, false
      ]).first
    else #invalid; trade neither long nor short
    end
    unless et.nil?
      et.assign_attributes ({:is_filled => true, :filled_at => DateTime.now})
      aTrade.assign_attributes ({:is_filled => true, :filled_at => DateTime.now})
      et.save
      aTrade.save
    end
  end
  def match_trades sTrade, bTrade
    
  end
  def update_high_bid
    price = trades.where( :is_filled => false,
                          :longTrue_shortFalse => true).maximum("entered_price")
    @high_bid = trades.where( :is_filled => false,
                              :longTrue_shortFalse => true,
                              :entered_price => price).first
  end
  def update_low_offer
    price = trades.where( :is_filled => false,
                          :longTrue_shortFalse => false).minimum("entered_price")
    @low_offer = trades.where(  :is_filled => false,
                                :longTrue_shortFalse => false,
                                :entered_price => price).first
  end
end

Ladders/Server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Ladders/Server/app/controllers/trades_controller.rb
class TradesController < ApplicationController
  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
#    render json: @trades
  end
  
  def myOpenTrades
    @trades = Trade.where(:user => params[:user], :is_filled => false)
    render json: @trades
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @trade = Trade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(params[:trade])

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render json: @trade, status: :created, location: @trade }
      else
        format.html { render action: "new" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @trade = Trade.find(params[:id])

    respond_to do |format|
      if @trade.update_attributes(params[:trade])
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end
end

Ladders/Server/app/helpers/application_helper.rb
module ApplicationHelper
end

Ladders/Server/app/helpers/trades_helper.rb
module TradesHelper
end

Ladders/Server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Server</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ladders/Server/app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ladders/Server/app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

Ladders/Server/app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<h3><%= @trades.count %> total trades </h3>
<% @trades.each do |trade| %>
  <tr>
    <td><%= link_to 'Show', trade %></td>
    <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
    <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trade', new_trade_path %>

Ladders/Server/app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

Ladders/Server/app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>